apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: sripriyan/auth:2.0
          imagePullPolicy: Always
          name: auth
          ports:
            - containerPort: 8080